name: sweetalert_angular_dart
description: SweetAlert for Angular Dart
version: 0.3.1
author: Nick Ng <ngyewch@gmail.com>
homepage: https://github.com/ngyewch/sweetalert-angular-dart

environment:
  sdk: '>=2.0.0 <3.0.0'


dependencies:
  angular: '>=5.0.0 <6.0.0'
  build_runner: '>=0.8.10 <0.11.0'

dev_dependencies:
  build_web_compilers: '>=0.3.6 <0.5.0'
