name: sweetalert_angular_dart
description: SweetAlert for Angular Dart
version: 0.3.1
author: Nick Ng <ngyewch@gmail.com>
homepage: https://github.com/ngyewch/sweetalert-angular-dart

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  angular: '>=4.0.0 <5.0.0'
  browser: '>=0.10.0 <0.11.0'

transformers:
- angular:
    entry_points: web/main.dart
